EzeLamar/sports-booking

.gitignore
README.md
app/firebase/config.js
package-lock.json
package.json

Changes:
* Add Firebase library
* Update README with the steps to attach the credentials of firebase Project.
* Ommit .env file

SB-9: Add Firebase and Credentials

---

docs/working_with_git.md

Changes:
* Add docs folder to include all the documentation for the project.
* Add document to describe the conventions using git for this project.

SB-23: Add work with git documentation

---

.storybook/main.ts
.storybook/preview.ts
README.md
app/components/Navbar.stories.tsx
app/context/AuthContext.tsx
package-lock.json
package.json

Changes:
* Add Storybook Library to the project.
* Add NavBar stories with and without user logged.

SB-28: Add Storybook and Navbar example

---

app/components/Navbar.tsx
app/components/OpenReservations/OpenReservationBadge.css
app/components/OpenReservations/OpenReservationBadge.tsx
app/components/OpenReservations/OpenReservationsSelector.css
app/components/OpenReservations/OpenReservationsSelector.stories.tsx
app/components/OpenReservations/OpenReservationsSelector.tsx
app/components/UI/Badge.stories.tsx
app/components/UI/BadgePill.tsx

Changes: 
* Add Badge Chain Component:
Extra:
* Update Navbar with Bootstrap style for logged email and Logout button

SB-32: Create Badge Chain Component

---

app/components/UI/DatePicker/DatePicker.stories.tsx
app/components/UI/DatePicker/DatePicker.tsx
package-lock.json
package.json

- Install the react-date-picker component library in project.
- Create a UI Component for this project to use the react-date-picker.
- Add Storybook examples.

SB-33: Added react-day-picker library

---

app/components/Courts/CourtSettings/CourtSettings.stories.tsx
app/components/Courts/CourtSettings/CourtSettings.tsx
app/components/OpenReservations/OpenReservationsSelector.stories.tsx
app/components/UI/Input/Input.stories.tsx
app/components/UI/Input/Input.tsx
app/components/UI/MultipleInputSelector/MultipleInputSelector.stories.tsx
app/components/UI/MultipleInputSelector/MultipleInputSelector.tsx
app/utils/Form/inputValidators.ts

Changes:
* Add Court Settings Component.
* Add MultipleInputSelector Component.
* Add `CHECKBOX_VALIDATOR `to be used with MultipleInputSelector.
Extra: 
* Add `MultipleInputSelector` Component to Input Story example
Court Settings Edit Mode:
Court Settings Show Mode:
Court Settings Validation Errors:

SB-41: Court Settings Card Component

---

app/components/UI/Loading/Loading.stories.tsx
app/components/UI/Loading/Loading.tsx
app/components/UI/Navbar/Navbar.stories.tsx
app/components/UI/Navbar/NavbarPlaceholder.stories.tsx
app/components/UI/Navbar/NavbarPlaceholder.tsx
app/context/AuthContext.tsx
app/layout.tsx
package-lock.json
package.json

Changes:
* Add Loading component with a spinner to show during the loading process.
* Add Navbar Placeholder to be shown until the user information is obtained.
* The Placeholder only has basic information for the testing process. In a future card, we will add the corresponding style.
Extra:
* Add bootstrap-icon library.

SB-50: Add NavbarPlaceholder and Loading components

---

app/components/Reservations/Reservation.tsx
app/components/UI/Navbar/Navbar.tsx
app/components/page.tsx
app/firebase/reservations/reservation.ts

- Create a service to handle the communication with Firebase for reservations-related operations.
- Define the data structure for reservations in Firebase
- Come up with the reservation class/model/representation as object in the frontend.
- A temporary page was created to visualize the results from the query

SB-46: Get reservations data from Firebase

---

app/components/Login/Signin/Signin.stories.tsx
app/components/Login/Signin/Signin.tsx
app/components/Login/Signup/Signup.stories.tsx
app/components/Login/Signup/Signup.tsx
app/components/UI/Form/Form.tsx
app/components/UI/Navbar/Navbar.tsx
app/components/UI/Navbar/NavbarPlaceholder.tsx
app/signin/page.tsx
app/signup/page.tsx
app/utils/Form/inputValidators.ts

Changes:
* Refactor of Signin and Signup Views using Form Component.
* Add Storybook for signin and signup components.
* NavBar:
* Add Login button to redirect to Signin View
* Remove Signup link to access Signup View (in a near future this view will be removed or restricted the access).
Signin View:
Signup View (removed from the NavBar):

SB-52: Improve Login View

---

.husky/pre-commit
README.md
app/admin/court/CourtSettingsView.tsx
app/components/Courts/CourtSettings/CourtSettings.stories.tsx
app/components/Courts/CourtSettings/CourtSettings.tsx
app/components/UI/DatePicker/DatePicker.stories.tsx
app/components/UI/DatePicker/DatePicker.tsx
app/components/UI/Input/Input.stories.tsx
app/components/UI/Input/Input.tsx
app/components/UI/MultipleInputSelector/MultipleInputSelector.stories.tsx
app/components/UI/MultipleInputSelector/MultipleInputSelector.tsx
app/components/UI/MultipleOptionsSelector/MultipleOptionsSelector.stories.tsx
app/components/UI/Navbar/Navbar.stories.tsx
app/components/UI/Navbar/Navbar.tsx
app/components/UI/SingleInputSelector/SingleInputSelector.stories.tsx
app/components/UI/SingleInputSelector/SingleInputSelector.tsx
app/components/page.tsx
app/firebase/courts/courts.ts
app/firebase/reservations/reservation.ts
app/signin/page.tsx
app/signup/page.tsx
app/utils/Error/ErrorHelper.ts
app/utils/Form/formHelper.ts
package.json

Changes:
* Fix Typescript error detected during the build process of the project.
* Update README with the steps to possibilitate the building process.  
* Add Error Helper for the catching process of the Promises.
* Add script to execute lint and prettier fixes with only one command.

SB-56: Fix Typescript build errors

---

.gitignore
README.md
firebase.json
package-lock.json
package.json

Changes:
* Add firebase-tools library
* Add Firebase Hosting Support
* Update Readme with the steps to initate a Firebase Hosting

SB-56: Add Firebase Hosting Config

---

.gitignore
app/admin/court/CourtSettingsView.tsx
app/components/UI/Navbar/Navbar.tsx
app/layout.tsx
package-lock.json
package.json

Changes:
* Fix build error to allow deploy Storybook project.
* Add  Speed Insights library to show metrics on Vercel.
* Add Serve library to test locally build and run the storybook project.

SB-3: Add Vercel Speed Insights for Deploy Metrics

---

app/components/Reservations/ReservationForm.stories.tsx
app/components/Reservations/ReservationForm.tsx
app/utils/Form/inputValidators.ts
package-lock.json

- Add a form component that will later be used to edit and show a reservation's information.
- A type was created for the form props, so that in the future a service can match between the model obtained from Firestore and the format required by the ReservationForm widget.

SB-51: Add a Reservation Form component

---

.storybook/preview.ts
app/admin/court/CourtSettingsView.tsx
app/globals.css
app/layout.tsx
app/signin/page.tsx
app/signup/page.tsx

Move all CSS imports to global css file

SB-65: Move all CSS imports to global css file

---

app/components/Reservations/ReservationForm.stories.tsx
app/components/Reservations/ReservationForm.tsx
app/components/UI/Input/Input.tsx
app/utils/Form/inputValidators.ts

Changes:
* Add ValidationType type.
* Add missing type on `RADIO_VALIDATOR `and `CHECKBOX_VALIDATOR`.
* ReservationForm:
* Add validation for the end hour.
* Add min max date range to input. 
Start hour equal to end hour error message:
Start hour greater than end hour error message:

SB-58: Add Reservation Form extra end hour validation

---

app/components/UI/Calendar/Calendar.tsx

Changes:
* Update Calendar events showing the Reservation Form Modal to add, show and update the events.

SB-63: Add Reservation Modal to Calendar

---

app/(admin)/reservations/[id]/page.tsx

Changes:
* Use the firebase reservation service to show the reservations on the calendar.

SB-68: Show Reservations on Calendar

---

app/(admin)/createReservation/page.tsx
app/(admin)/getAllReservations/page.tsx
app/(admin)/reservations/[id]/page.tsx
app/components/Reservations/Reservation.tsx
app/components/Reservations/ReservationForm.tsx
app/components/Reservations/values.ts
app/components/UI/Calendar/Calendar.stories.tsx
app/components/UI/Calendar/Calendar.tsx
app/components/UI/Calendar/module.ts
app/firebase/reservations/reservation.ts

Changes:
* Allows adding reservations to Firestore by the Reservation Calendar.
* Create NewReservationType to represent the draft Reservation without the id.

SB-74: Add Reservation on FiresStore by Calendar

---

app/(admin)/courts/[id]/page.tsx
app/components/UI/Navbar/Navbar.tsx
app/components/UI/Navbar/NavbarPlaceholder.tsx
app/page.tsx

Changes:
* Refactor Home screen to only be visible when you are not logged in and hidden when you are not.
* Move the Login button from the Navbar to Home Screen.
* Small style changes

SB-79: Move Login Button to Home Screen

---

app/(admin)/reservations/[id]/page.tsx
app/firebase/reservations/reservation.ts

Changes:
* Filter the reservations fetched by the court that they belongs

SB-78  Show Reservations on Calendar by Court

---

app/(admin)/createReservation/page.tsx
app/(admin)/reservations/[id]/page.tsx
app/components/Reservations/ReservationForm.tsx
app/components/Reservations/values.ts
app/components/UI/Calendar/Calendar.stories.tsx
app/components/UI/Calendar/Calendar.tsx
app/components/UI/Calendar/model.ts
app/firebase/reservations/model.ts
app/firebase/reservations/reservation.ts

PART 2/3
Changes:
* Add price field on the Reservation Form.
* Update CRUD reservation adding the price field.

SB-66: Add price field in Reservation Form and Calendar

---

app/(admin)/createReservation/page.tsx
app/(admin)/reservations/[id]/page.tsx
app/components/Reservations/ReservationForm.tsx
app/components/Reservations/values.ts
app/components/UI/Calendar/Calendar.css
app/components/UI/Calendar/Calendar.stories.tsx
app/components/UI/Calendar/Calendar.tsx
app/components/UI/Calendar/model.ts
app/firebase/reservations/model.ts
app/firebase/reservations/reservation.ts
app/utils/Form/inputValidators.ts

Part 3/3
Changes:
* Add status field on Reservation Form.
* Update CRUD reservation adding the status field.
* Update Calendar
* Add red border style for events with status booked (not paid).
* Add grey color style for events with status canceled.

SB-66: Add status field on Reservations Form and Calendar

---

app/components/UI/Form/Form.tsx

Changes:
* Disable buttons and fields on Forms during the submit process.
* Add a spinner at the submit button during the submit process.

SB-83: Disable fields and buttons during submit process

---

.env.example
README.md
app/firebase/README.md

Update readme file with a proper description of the project, the technologies used, the process, contributors, etc.

SB 71: Update Readme file

---

app/(admin)/reservations/[id]/page.tsx
app/components/Courts/CourtSettings/CourtSettings.stories.tsx
app/components/Courts/CourtSettings/CourtSettings.tsx
app/components/Reservations/ReservationDetails.tsx
app/components/Reservations/ReservationForm.tsx
app/components/Reservations/ReservationModal.tsx
app/components/UI/Calendar/Calendar.css
app/components/UI/Calendar/Calendar.tsx
app/components/UI/Calendar/CalendarToolbar/CalendarToolbar.tsx
app/components/UI/Input/Input.tsx
app/components/UI/Modal/Drawer.tsx
app/components/UI/Navbar/Navbar.tsx
app/components/UI/Select/SelectLinked.tsx
app/context/CourtContext.tsx
app/firebase/courts/courts.ts
app/globals.css
app/signup/page.tsx

Changes:
* Add Style to Calendar
* Add Custom toolbar
* Add Darkmode support
* Improve Drawer
* Add Reservation Detail View for the drawer when is not in edit mode.
* Calculate the price for Class, Tournament and Match by the duration of the reservation.

SB-93: Add Style to Calendar and Improve Drawer

---

app/components/Reservations/ReservationModal.tsx

SB-93: Fix Height on Drawer

---

app/components/Clients/ClientDetails.tsx
app/components/Reservations/ReservationForm.tsx
app/components/UI/Modal/ModalConfirmDelete/ModalConfirmDelete.tsx

Changes:
* Add confirmation modal to delete Client and Reservation

SB-96: Add Confirmation Modal to delete Client and Reservation

---

app/(admin)/reservations/[id]/page.tsx
app/components/Clients/ClientDetails.tsx
app/components/Reservations/ReservationForm.stories.tsx
app/components/Reservations/ReservationForm.tsx
app/components/Reservations/ReservationModal.tsx
app/components/UI/Calendar/Calendar.css
app/components/UI/Calendar/Calendar.stories.tsx
app/components/UI/Calendar/Calendar.tsx
app/components/UI/Calendar/CalendarModalFilter/CalendarModalFilter.tsx
app/components/UI/Calendar/CalendarModalFilter/FilterForm.tsx
app/components/UI/Calendar/CalendarToolbar/CalendarToolbar.tsx
app/components/UI/Calendar/model.ts
app/components/UI/Modal/Drawer.tsx
app/hooks/useReservations.tsx
app/layout.tsx
app/signup/page.tsx

Changes:
* Add Reservation Filter by Client, Type and Status.
* Fix problems with drawer.
* Move Delete Reservation button to Reservation Details.
* Add counter and details for the reservations on Client Details view.

SB-97: Add Reservation Filters on Calendar

---

app/(admin)/clients/page.tsx
app/(admin)/courts/[id]/page.tsx
app/(admin)/courts/new/page.tsx
app/(admin)/courts/page.tsx
app/components/Clients/ClientCard.tsx
app/components/Clients/View/ClientsView.tsx
app/components/Courts/CourtCard.tsx
app/components/Courts/CourtDetails.tsx
app/components/Courts/View/CourtsView.tsx
app/components/UI/Input/ButtonGroup.tsx
app/firebase/courts/courts.ts

Changes:
* Add the possibility to add and delete courts
* Fix some responsive problems on clientsView and courtViews
* Refactor ButtonGroup for 'Días Habiles' selector.

SB-98: Add Court View to Add new Courts
